export const NEWS_LOAD = "NEWS_LOAD"
export const STORY_LOAD = "STORY_LOAD"
export const COMMENTS_LOAD = "COMMENT_LOAD"
export const UPDATE_NUMBERS_OF_COMMENTS = "UPDATE_NUMBERS_OF_COMMENTS"

export const LOADER_DISPLAY_ON = 'LOADER_DISPLAY_ON'; 
export const LOADER_DISPLAY_OFF = 'LOADER_DISPLAY_OFF'; 